INSERT INTO sponsor ("id_sponsor", "nama_sponsor", "email_sponsor", "provinsi", "kabupaten_kota", "kecamatan", "desa_kelurahan", "kode_pos", "alamat") VALUES
('SPONS001', 'Nusantara Sponsor 1', 'sponsor1@mail.id', 'Bali', 'Bangli', 'Ketintang', 'Kalibaru', '95441', 'Jl. Gajah Mada No.97, Kalibaru, Ketintang, Bangli, Bali, 95441'),
('SPONS002', 'Makmur Abadi Sponsor 2', 'sponsor2@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Ketintang', '26858', 'Jl. Diponegoro No.186, Ketintang, Sawahan, Gianyar, Bali, 26858'),
('SPONS003', 'Cahaya Jaya Sponsor 3', 'sponsor3@mail.id', 'Jawa Timur', 'Surabaya', 'Wonokromo', 'Darmo', '60241', 'Jl. Raya Darmo No.55, Darmo, Wonokromo, Surabaya, Jawa Timur, 60241'),
('SPONS004', 'Prima Sentosa Sponsor 4', 'sponsor4@sponsorship.co.id', 'Jawa Barat', 'Bandung', 'Coblong', 'Dago', '40135', 'Jl. Ir. H. Juanda No.102, Dago, Coblong, Bandung, Jawa Barat, 40135'),
('SPONS005', 'Bersinar Mandiri Sponsor 5', 'sponsor5@mail.id', 'Jawa Tengah', 'Semarang', 'Tembalang', 'Sendangmulyo', '50272', 'Jl. Melati No.22, Sendangmulyo, Tembalang, Semarang, Jawa Tengah, 50272'),
('SPONS006', 'Sejahtera Abadi Sponsor 6', 'sponsor6@sponsorship.co.id', 'DKI Jakarta', 'Jakarta Selatan', 'Kebayoran Baru', 'Petogogan', '12170', 'Jl. Wijaya II No.8, Petogogan, Kebayoran Baru, Jakarta Selatan, 12170'),
('SPONS007', 'Gemilang Nusantara Sponsor 7', 'sponsor7@mail.id', 'Yogyakarta', 'Sleman', 'Depok', 'Caturtunggal', '55281', 'Jl. Kaliurang KM 5 No.21, Caturtunggal, Depok, Sleman, Yogyakarta, 55281'),
('SPONS008', 'Bumi Indah Sponsor 8', 'sponsor8@sponsorship.co.id', 'Sumatera Utara', 'Medan', 'Medan Kota', 'Sukaramai', '20212', 'Jl. Pelita No.10, Sukaramai, Medan Kota, Medan, Sumatera Utara, 20212'),
('SPONS009', 'Karya Sejati Sponsor 9', 'sponsor9@mail.id', 'Jawa Timur', 'Sidoarjo', 'Taman', 'Geluran', '61257', 'Jl. Raya Geluran No.15, Geluran, Taman, Sidoarjo, Jawa Timur, 61257'),
('SPONS010', 'Samudra Sponsor 10', 'sponsor10@sponsorship.co.id', 'Banten', 'Tangerang', 'Karawaci', 'Cimone', '15114', 'Jl. Ahmad Yani No.35, Cimone, Karawaci, Tangerang, Banten, 15114'),
('SPONS011', 'Langit Cerah Sponsor 11', 'sponsor11@mail.id', 'Bali', 'Denpasar', 'Denpasar Barat', 'Padangsambian', '80119', 'Jl. Gunung Agung No.14, Padangsambian, Denpasar Barat, Denpasar, Bali, 80119'),
('SPONS012', 'Sinar Abadi Sponsor 12', 'sponsor12@sponsorship.co.id', 'Jawa Tengah', 'Solo', 'Laweyan', 'Sondakan', '57148', 'Jl. Slamet Riyadi No.41, Sondakan, Laweyan, Solo, Jawa Tengah, 57148'),
('SPONS013', 'Mega Utama Sponsor 13', 'sponsor13@mail.id', 'Jawa Timur', 'Malang', 'Lowokwaru', 'Tlogomas', '65144', 'Jl. Mawar No.23, Tlogomas, Lowokwaru, Malang, Jawa Timur, 65144'),
('SPONS014', 'Surya Kencana Sponsor 14', 'sponsor14@sponsorship.co.id', 'Lampung', 'Bandar Lampung', 'Kedaton', 'Penengahan', '35141', 'Jl. Teuku Umar No.47, Penengahan, Kedaton, Bandar Lampung, 35141'),
('SPONS015', 'Sentra Jaya Sponsor 15', 'sponsor15@mail.id', 'Bali', 'Badung', 'Kuta', 'Legian', '80361', 'Jl. Legian No.3, Legian, Kuta, Badung, Bali, 80361'),
('SPONS016', 'Andalan Bersama Sponsor 16', 'sponsor16@sponsorship.co.id', 'Jawa Tengah', 'Magelang', 'Magelang Tengah', 'Cacaban', '56122', 'Jl. Pemuda No.60, Cacaban, Magelang Tengah, Magelang, Jawa Tengah, 56122'),
('SPONS017', 'Makmur Raya Sponsor 17', 'sponsor17@mail.id', 'Jawa Timur', 'Blitar', 'Sananwetan', 'Gedog', '66137', 'Jl. Kenari No.18, Gedog, Sananwetan, Blitar, Jawa Timur, 66137'),
('SPONS018', 'Pesona Indah Sponsor 18', 'sponsor18@sponsorship.co.id', 'Sulawesi Selatan', 'Makassar', 'Panakkukang', 'Pampang', '90231', 'Jl. Toddopuli No.29, Pampang, Panakkukang, Makassar, Sulawesi Selatan, 90231'),
('SPONS019', 'Citra Mandiri Sponsor 19', 'sponsor19@mail.id', 'Jawa Barat', 'Bogor', 'Tanah Sareal', 'Kedung Badak', '16164', 'Jl. Sholeh Iskandar No.88, Kedung Badak, Tanah Sareal, Bogor, Jawa Barat, 16164'),
('SPONS020', 'Elang Group Sponsor 20', 'sponsor20@sponsorship.co.id', 'Jawa Timur', 'Probolinggo', 'Mayangan', 'Mangunharjo', '67219', 'Jl. Suroyo No.19, Mangunharjo, Mayangan, Probolinggo, Jawa Timur, 67219'),
('SPONS021', 'Kencana Gemilang Sponsor 21', 'sponsor21@mail.id', 'Jawa Barat', 'Bekasi', 'Bekasi Selatan', 'Kayuringin', '17144', 'Jl. Ahmad Yani No.11, Kayuringin, Bekasi Selatan, Bekasi, 17144'),
('SPONS022', 'Mentari Sejahtera Sponsor 22', 'sponsor22@sponsorship.co.id', 'Sumatera Barat', 'Padang', 'Padang Barat', 'Kampung Pondok', '25111', 'Jl. Sudirman No.10, Kampung Pondok, Padang Barat, Padang, 25111'),
('SPONS023', 'Mitra Bersama Sponsor 23', 'sponsor23@mail.id', 'Jawa Timur', 'Kediri', 'Mojoroto', 'Banjaran', '64112', 'Jl. Joyoboyo No.40, Banjaran, Mojoroto, Kediri, Jawa Timur, 64112'),
('SPONS024', 'Surya Mega Sponsor 24', 'sponsor24@sponsorship.co.id', 'Kalimantan Selatan', 'Banjarmasin', 'Banjarmasin Tengah', 'Melayu', '70122', 'Jl. A. Yani No.15, Melayu, Banjarmasin Tengah, Banjarmasin, 70122'),
('SPONS025', 'Nusa Jaya Sponsor 25', 'sponsor25@mail.id', 'Jawa Tengah', 'Purwokerto', 'Purwokerto Timur', 'Karang Klesem', '53144', 'Jl. Jenderal Sudirman No.13, Karang Klesem, Purwokerto Timur, Purwokerto, 53144'),
('SPONS026', 'Utama Group Sponsor 26', 'sponsor26@sponsorship.co.id', 'Jawa Timur', 'Jember', 'Patrang', 'Tegal Besar', '68117', 'Jl. Jawa No.5, Tegal Besar, Patrang, Jember, Jawa Timur, 68117'),
('SPONS027', 'Cakra Mandiri Sponsor 27', 'sponsor27@mail.id', 'Jawa Barat', 'Depok', 'Beji', 'Kukusan', '16425', 'Jl. Margonda Raya No.70, Kukusan, Beji, Depok, Jawa Barat, 16425'),
('SPONS028', 'Trisakti Sponsor 28', 'sponsor28@sponsorship.co.id', 'Kalimantan Timur', 'Balikpapan', 'Balikpapan Utara', 'Gunung Samarinda', '76125', 'Jl. MT Haryono No.9, Gunung Samarinda, Balikpapan Utara, Balikpapan, 76125'),
('SPONS029', 'Satu Visi Sponsor 29', 'sponsor29@mail.id', 'Bali', 'Tabanan', 'Kediri', 'Beringkit', '82121', 'Jl. Raya Kediri No.8, Beringkit, Kediri, Tabanan, Bali, 82121'),
('SPONS030', 'Garuda Abadi Sponsor 30', 'sponsor30@sponsorship.co.id', 'Jawa Timur', 'Madiun', 'Manguharjo', 'Winongo', '63111', 'Jl. Panglima Sudirman No.10, Winongo, Manguharjo, Madiun, 63111'),
('SPONS031', 'Mega Lestari Sponsor 31', 'sponsor31@mail.id', 'Banten', 'Cilegon', 'Cibeber', 'Kedaleman', '42424', 'Jl. Raya Merak No.12, Kedaleman, Cibeber, Cilegon, Banten, 42424'),
('SPONS032', 'Andromeda Sponsor 32', 'sponsor32@sponsorship.co.id', 'Yogyakarta', 'Bantul', 'Banguntapan', 'Potorono', '55194', 'Jl. Imogiri Timur No.30, Potorono, Banguntapan, Bantul, 55194'),
('SPONS033', 'Global Media Sponsor 33', 'sponsor33@mail.id', 'Jawa Timur', 'Pasuruan', 'Gadingrejo', 'Panggungrejo', '67137', 'Jl. Soekarno Hatta No.20, Panggungrejo, Gadingrejo, Pasuruan, 67137'),
('SPONS034', 'Alpha Vision Sponsor 34', 'sponsor34@sponsorship.co.id', 'Jawa Tengah', 'Tegal', 'Margadana', 'Kaligangsa', '52141', 'Jl. Raya Kaligangsa No.7, Margadana, Tegal, Jawa Tengah, 52141'),
('SPONS035', 'Omega Utama Sponsor 35', 'sponsor35@mail.id', 'Aceh', 'Banda Aceh', 'Kuta Alam', 'Beurawe', '23125', 'Jl. Teuku Umar No.16, Beurawe, Kuta Alam, Banda Aceh, 23125'),
('SPONS036', 'Nirwana Sponsor 36', 'sponsor36@sponsorship.co.id', 'Jawa Timur', 'Banyuwangi', 'Banyuwangi', 'Sobo', '68418', 'Jl. Ahmad Yani No.77, Sobo, Banyuwangi, Jawa Timur, 68418'),
('SPONS037', 'Mandiri Jaya Sponsor 37', 'sponsor37@mail.id', 'Sumatera Selatan', 'Palembang', 'Ilir Timur I', 'Sungai Buah', '30111', 'Jl. Kapten A Rivai No.9, Sungai Buah, Ilir Timur I, Palembang, 30111'),
('SPONS038', 'Beta Group Sponsor 38', 'sponsor38@sponsorship.co.id', 'Sulawesi Tenggara', 'Kendari', 'Mandonga', 'Korumba', '93121', 'Jl. Ahmad Yani No.15, Korumba, Mandonga, Kendari, 93121'),
('SPONS039', 'Delta Sponsor 39', 'sponsor39@mail.id', 'Jawa Barat', 'Cimahi', 'Cimahi Selatan', 'Leuwigajah', '40532', 'Jl. Amir Machmud No.10, Leuwigajah, Cimahi Selatan, Cimahi, 40532'),
('SPONS040', 'Harmony Sponsor 40', 'sponsor40@sponsorship.co.id', 'Jawa Timur', 'Gresik', 'Gresik', 'Sidokumpul', '61111', 'Jl. Dr. Wahidin Sudirohusodo No.88, Sidokumpul, Gresik, Jawa Timur, 61111'),
('SPONS041', 'Sejahtera Jaya Sponsor 41', 'sponsor41@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '38126', 'Jl. Srikandi No.14, Ketintang, Lowokwaru, Bangli, Bali, 38126'),
('SPONS042', 'Berkah Mandiri Sponsor 42', 'sponsor42@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '92473', 'Jl. Hasanudin No.77, Kalibaru, Blimbing, Gianyar, Bali, 92473'),
('SPONS043', 'Makmur Abadi Sponsor 43', 'sponsor43@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '57839', 'Jl. Veteran No.63, Ketintang, Sukun, Bangli, Bali, 57839'),
('SPONS044', 'Gemilang Nusantara Sponsor 44', 'sponsor44@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '92651', 'Jl. Hayam Wuruk No.81, Kalibaru, Lowokwaru, Gianyar, Bali, 92651'),
('SPONS045', 'Sentosa Group Sponsor 45', 'sponsor45@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '61584', 'Jl. Ijen No.9, Ketintang, Klojen, Bangli, Bali, 61584'),
('SPONS046', 'Maju Bersama Sponsor 46', 'sponsor46@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '47328', 'Jl. Majapahit No.102, Kalibaru, Sawahan, Gianyar, Bali, 47328'),
('SPONS047', 'Sinar Abadi Sponsor 47', 'sponsor47@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '74583', 'Jl. Soekarno Hatta No.56, Ketintang, Lowokwaru, Bangli, Bali, 74583'),
('SPONS048', 'Makmur Sejahtera Sponsor 48', 'sponsor48@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '30217', 'Jl. Imam Bonjol No.93, Kalibaru, Blimbing, Gianyar, Bali, 30217'),
('SPONS049', 'Nusantara Sponsor 49', 'sponsor49@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '48712', 'Jl. Trunojoyo No.35, Ketintang, Sukun, Bangli, Bali, 48712'),
('SPONS050', 'Berkah Raya Sponsor 50', 'sponsor50@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '91623', 'Jl. MT Haryono No.74, Kalibaru, Lowokwaru, Gianyar, Bali, 91623'),
('SPONS051', 'Mandiri Makmur Sponsor 51', 'sponsor51@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '56381', 'Jl. Arjuna No.62, Ketintang, Klojen, Bangli, Bali, 56381'),
('SPONS052', 'Sejahtera Bersama Sponsor 52', 'sponsor52@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '41572', 'Jl. Pahlawan No.21, Kalibaru, Sawahan, Gianyar, Bali, 41572'),
('SPONS053', 'Cahaya Nusantara Sponsor 53', 'sponsor53@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '71248', 'Jl. Rajawali No.46, Ketintang, Lowokwaru, Bangli, Bali, 71248'),
('SPONS054', 'Gemilang Abadi Sponsor 54', 'sponsor54@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '68521', 'Jl. Pattimura No.15, Kalibaru, Blimbing, Gianyar, Bali, 68521'),
('SPONS055', 'Mitra Mandiri Sponsor 55', 'sponsor55@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '32654', 'Jl. Simpang Lima No.71, Ketintang, Sukun, Bangli, Bali, 32654'),
('SPONS056', 'Harapan Baru Sponsor 56', 'sponsor56@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '89347', 'Jl. Majapahit No.52, Kalibaru, Lowokwaru, Gianyar, Bali, 89347'),
('SPONS057', 'Berkah Abadi Sponsor 57', 'sponsor57@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '49871', 'Jl. Diponegoro No.85, Ketintang, Klojen, Bangli, Bali, 49871'),
('SPONS058', 'Nusantara Jaya Sponsor 58', 'sponsor58@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '27865', 'Jl. Letjen Sutoyo No.33, Kalibaru, Sawahan, Gianyar, Bali, 27865'),
('SPONS059', 'Makmur Sentosa Sponsor 59', 'sponsor59@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '74629', 'Jl. Suryo No.28, Ketintang, Lowokwaru, Bangli, Bali, 74629'),
('SPONS060', 'Cemerlang Sponsor 60', 'sponsor60@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '31427', 'Jl. Basuki Rahmat No.42, Kalibaru, Blimbing, Gianyar, Bali, 31427'),
('SPONS061', 'Sentosa Abadi Sponsor 61', 'sponsor61@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '57382', 'Jl. Letjen Suprapto No.31, Ketintang, Sukun, Bangli, Bali, 57382'),
('SPONS062', 'Harapan Makmur Sponsor 62', 'sponsor62@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '84192', 'Jl. Gajah Mada No.96, Kalibaru, Lowokwaru, Gianyar, Bali, 84192'),
('SPONS063', 'Mitra Abadi Sponsor 63', 'sponsor63@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '23184', 'Jl. Panglima Sudirman No.47, Ketintang, Klojen, Bangli, Bali, 23184'),
('SPONS064', 'Bersatu Jaya Sponsor 64', 'sponsor64@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '47356', 'Jl. Hayam Wuruk No.54, Kalibaru, Sawahan, Gianyar, Bali, 47356'),
('SPONS065', 'Makmur Sejati Sponsor 65', 'sponsor65@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '75312', 'Jl. Diponegoro No.88, Ketintang, Lowokwaru, Bangli, Bali, 75312'),
('SPONS066', 'Cahaya Mandiri Sponsor 66', 'sponsor66@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '61648', 'Jl. Imam Bonjol No.79, Kalibaru, Blimbing, Gianyar, Bali, 61648'),
('SPONS067', 'Gemilang Sejahtera Sponsor 67', 'sponsor67@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '82459', 'Jl. Arjuno No.64, Ketintang, Sukun, Bangli, Bali, 82459'),
('SPONS068', 'Harapan Indah Sponsor 68', 'sponsor68@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '57192', 'Jl. MT Haryono No.19, Kalibaru, Lowokwaru, Gianyar, Bali, 57192'),
('SPONS069', 'Berkah Mandiri Sponsor 69', 'sponsor69@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '96583', 'Jl. WR Supratman No.76, Ketintang, Klojen, Bangli, Bali, 96583'),
('SPONS070', 'Maju Sejahtera Sponsor 70', 'sponsor70@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '25984', 'Jl. S. Parman No.32, Kalibaru, Sawahan, Gianyar, Bali, 25984'),
('SPONS071', 'Nusantara Group Sponsor 71', 'sponsor71@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '81236', 'Jl. Gubernur Suryo No.61, Ketintang, Lowokwaru, Bangli, Bali, 81236'),
('SPONS072', 'Sejahtera Abadi Sponsor 72', 'sponsor72@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '38412', 'Jl. Panglima Polim No.11, Kalibaru, Blimbing, Gianyar, Bali, 38412'),
('SPONS073', 'Makmur Bersatu Sponsor 73', 'sponsor73@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '46371', 'Jl. Slamet Riyadi No.84, Ketintang, Sukun, Bangli, Bali, 46371'),
('SPONS074', 'Harapan Jaya Sponsor 74', 'sponsor74@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '28594', 'Jl. Majapahit No.18, Kalibaru, Lowokwaru, Gianyar, Bali, 28594'),
('SPONS075', 'Gemilang Raya Sponsor 75', 'sponsor75@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '47136', 'Jl. Gajah Mada No.95, Ketintang, Klojen, Bangli, Bali, 47136'),
('SPONS076', 'Mitra Sejahtera Sponsor 76', 'sponsor76@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '94625', 'Jl. Diponegoro No.61, Kalibaru, Sawahan, Gianyar, Bali, 94625'),
('SPONS077', 'Berkah Lestari Sponsor 77', 'sponsor77@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '32974', 'Jl. Veteran No.67, Ketintang, Lowokwaru, Bangli, Bali, 32974'),
('SPONS078', 'Cahaya Sentosa Sponsor 78', 'sponsor78@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '67184', 'Jl. Basuki Rahmat No.53, Kalibaru, Blimbing, Gianyar, Bali, 67184'),
('SPONS079', 'Harapan Bersama Sponsor 79', 'sponsor79@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '78216', 'Jl. Imam Bonjol No.39, Ketintang, Sukun, Bangli, Bali, 78216'),
('SPONS080', 'Makmur Jaya Sponsor 80', 'sponsor80@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '52649', 'Jl. Trunojoyo No.44, Kalibaru, Lowokwaru, Gianyar, Bali, 52649'),
('SPONS081', 'Nusantara Sejahtera Sponsor 81', 'sponsor81@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '46297', 'Jl. Hayam Wuruk No.91, Ketintang, Klojen, Bangli, Bali, 46297'),
('SPONS082', 'Gemilang Mandiri Sponsor 82', 'sponsor82@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '68243', 'Jl. Pahlawan No.47, Kalibaru, Sawahan, Gianyar, Bali, 68243'),
('SPONS083', 'Makmur Lestari Sponsor 83', 'sponsor83@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '82564', 'Jl. Ijen No.57, Ketintang, Lowokwaru, Bangli, Bali, 82564'),
('SPONS084', 'Berkah Sentosa Sponsor 84', 'sponsor84@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '49573', 'Jl. Gajah Mada No.92, Kalibaru, Blimbing, Gianyar, Bali, 49573'),
('SPONS085', 'Sejahtera Raya Sponsor 85', 'sponsor85@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '24196', 'Jl. Basuki Rahmat No.68, Ketintang, Sukun, Bangli, Bali, 24196'),
('SPONS086', 'Cahaya Abadi Sponsor 86', 'sponsor86@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '71328', 'Jl. MT Haryono No.26, Kalibaru, Lowokwaru, Gianyar, Bali, 71328'),
('SPONS087', 'Harapan Maju Sponsor 87', 'sponsor87@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '97534', 'Jl. Diponegoro No.73, Ketintang, Klojen, Bangli, Bali, 97534'),
('SPONS088', 'Mitra Makmur Sponsor 88', 'sponsor88@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '58249', 'Jl. Imam Bonjol No.35, Kalibaru, Sawahan, Gianyar, Bali, 58249'),
('SPONS089', 'Gemilang Jaya Sponsor 89', 'sponsor89@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '38267', 'Jl. Panglima Sudirman No.77, Ketintang, Lowokwaru, Bangli, Bali, 38267'),
('SPONS090', 'Sentosa Bersatu Sponsor 90', 'sponsor90@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '74618', 'Jl. Veteran No.43, Kalibaru, Blimbing, Gianyar, Bali, 74618'),
('SPONS091', 'Makmur Bersama Sponsor 91', 'sponsor91@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '94625', 'Jl. WR Supratman No.32, Ketintang, Sukun, Bangli, Bali, 94625'),
('SPONS092', 'Nusantara Maju Sponsor 92', 'sponsor92@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '25784', 'Jl. Majapahit No.51, Kalibaru, Lowokwaru, Gianyar, Bali, 25784'),
('SPONS093', 'Harapan Sejahtera Sponsor 93', 'sponsor93@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '67231', 'Jl. Arjuna No.36, Ketintang, Klojen, Bangli, Bali, 67231'),
('SPONS094', 'Bersatu Mandiri Sponsor 94', 'sponsor94@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '91357', 'Jl. S. Parman No.63, Kalibaru, Sawahan, Gianyar, Bali, 91357'),
('SPONS095', 'Makmur Raya Sponsor 95', 'sponsor95@mail.id', 'Bali', 'Bangli', 'Lowokwaru', 'Ketintang', '53418', 'Jl. Gubernur Suryo No.58, Ketintang, Lowokwaru, Bangli, Bali, 53418'),
('SPONS096', 'Cemerlang Mandiri Sponsor 96', 'sponsor96@sponsorship.co.id', 'Bali', 'Gianyar', 'Blimbing', 'Kalibaru', '79463', 'Jl. Rajawali No.88, Kalibaru, Blimbing, Gianyar, Bali, 79463'),
('SPONS097', 'Gemilang Makmur Sponsor 97', 'sponsor97@mail.id', 'Bali', 'Bangli', 'Sukun', 'Ketintang', '61597', 'Jl. Diponegoro No.19, Ketintang, Sukun, Bangli, Bali, 61597'),
('SPONS098', 'Berkah Mandiri Sponsor 98', 'sponsor98@sponsorship.co.id', 'Bali', 'Gianyar', 'Lowokwaru', 'Kalibaru', '35126', 'Jl. Panglima Polim No.71, Kalibaru, Lowokwaru, Gianyar, Bali, 35126'),
('SPONS099', 'Maju Abadi Sponsor 99', 'sponsor99@mail.id', 'Bali', 'Bangli', 'Klojen', 'Ketintang', '46852', 'Jl. Letjen Sutoyo No.41, Ketintang, Klojen, Bangli, Bali, 46852'),
('SPONS100', 'Nusantara Abadi Sponsor 100', 'sponsor100@sponsorship.co.id', 'Bali', 'Gianyar', 'Sawahan', 'Kalibaru', '97264', 'Jl. MT Haryono No.59, Kalibaru, Sawahan, Gianyar, Bali, 97264');
